# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AdminandUser.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from userlogin import Ui_Formm
from Login import Ui_Form2
from Signup import Ui_Form7

class Ui_Form(object):



    def __init__(self):
        pass

    def userloginwindow(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Formm()
        self.ui.setupUi(self.window)
        Form.hide()
        self.window.show()
    def adimloginwindow(self):
        self.window1 = QtWidgets.QWidget()
        self.ui = Ui_Form2()
        self.ui.setupUi(self.window1)
        Form.hide()
        self.window1.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(540, 403)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-20, 0, 571, 571))
        self.label.setStyleSheet("background-color:rgba(16,30,41,240);\n"
"border-radius: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(120, 210, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color:rgba(2,65,118,255);\n"
"color:rgba(255,255,255,200);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2,65,118,100);\n"
"background-position:calc(100% - 10px)center;\n"
"}\n"
"QPushButton#pushButton{\n"
"background-color:rgba(2,65,118,200);\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.adimloginwindow)

        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(270, 210, 131, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka Subheading")
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton#evilButton {\n"
"    background-color:rgb(85, 85, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-color: beige;\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"}\n"
"QPushButton#evilButton {\n"
"    background-color: red;\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.userloginwindow)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 160, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Bauhaus 93")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Admin"))
        self.pushButton_3.setText(_translate("Form", "User"))
        self.label_3.setText(_translate("Form", "Restaurant Management System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())