# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dashboardadmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
from adduser import Ui_Form5
from random import sample
import matplotlib.pyplot as plt
import matplotlib.colors as pltc
from receipt import Ui_receipt



con = sqlite3.connect("data.db")
mydb = con.cursor()


con.commit()


class dashborad(object):



    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 661)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -20, 871, 721))
        self.label.setStyleSheet("background-image: url(images/Dark Food Photography DIY and Prop Tips - Blogtastic Food.jpeg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/Download free illustration of Abstract background dark blue wallpaper.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(200, 180, 511, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.tableWidget.setStyleSheet("border-style: outset;\n"
"border-width: 5px;\n"
"border-color: black;\n"
"background-color: gray;\n"
"color: black;")
        self.tableWidget.setRowCount(12)
        self.tableWidget.setColumnCount(17)
        self.tableWidget.setObjectName("tableWidget")
        self.verticalLayout.addWidget(self.tableWidget)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 430, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border-style: outset;\n"
"border-radius: 30px;\n"
"border-width: 5px;\n"
"border-color: gray;\n"
"background-color: white;\n"
"color: black;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.chartdata)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 230, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(8)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-style: outset;\n"
"border-radius: 30px;\n"
"border-width: 5px;\n"
"border-color: gray;\n"
"background-color: white;\n"
"color: black;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.adduserdata)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(360, 570, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("border-style: outset;\n"
"border-width: 5px;\n"
"border-color: gray;\n"
"background-color: white;\n"
"color: black;")
        self.lineEdit.setText("")
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 330, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(8)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border-style: outset;\n"
"border-radius: 30px;\n"
"border-width: 5px;\n"
"border-color: gray;\n"
"background-color: white;\n"
"color: black;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.gettalldata)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 50, 451, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;\n"
"border-style: outset;\n"
"border-radius:10px;\n"
"border-width: 5px;\n"
"border-color: gray;")
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 560, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-style: outset;\n"
"border-radius: 30px;\n"
"border-width: 5px;\n"
"border-color: gray;\n"
"background-color: white;\n"
"color: black;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.information)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.tableWidget.setHorizontalHeaderLabels(["Order Number", "Boolani", "Qabuli", "Mantu", "Chiken Karahi", "Chiken Fajita", "Soda", "Pepsi", "Sprite"," Coca Cola", "Fruity Pebble", "Chocolate Cake", "Key Lime Pie ", "Brownie", "Cheese Cake", "Total", "Net Profit"])

    def gettalldata(self):
        conn = sqlite3.connect("data.db")
        count = con.execute("SELECT * FROM 'dash'")
        self.display(count)

    def display(self, count):
        conn = sqlite3.connect("data.db")
        print("database Connected")
        self.tableWidget.setRowCount(12)
        for row_number, row_data in enumerate(count):
            self.tableWidget.insertRow(row_number)
            for column_number, data in enumerate(row_data):
                self.tableWidget.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))
            conn.close()

    def adduserdata(self):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form5()
        self.ui.setupUi(self.Form)
        self.Form.show()


    def chartdata(self):
        sales = [15, 35, 50]
        colors = sample(list(pltc.cnames.values()), len(sales))
        ['#FFA500', '#A52A2A', '#008000']
        salesnaeme = ['Daily', 'Monthly', ' Yearly ']
        space_slice = [0.07, 0.3, 0]
        plt.figure(figsize=(6, 5))
        plt.pie(sales, labels=salesnaeme, autopct='%1.1f%%', shadow=False, explode=space_slice, colors=colors)
        plt.title("Sales Summary")
        plt.legend(salesnaeme, loc=(-0.25, 0.7), shadow=False)
        plt.show()

    def information(self):
        self.window11 = QtWidgets.QMainWindow()
        self.ui = Ui_receipt()
        self.ui.setupUi(self.window11)

        self.window11.show()








    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Chart"))
        self.pushButton.setText(_translate("MainWindow", "Add User"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", " Enter ID"))
        self.pushButton_3.setText(_translate("MainWindow", "Show"))
        self.label_2.setText(_translate("MainWindow", "D a s h b o a r d"))
        self.pushButton_4.setText(_translate("MainWindow", "Run"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = dashborad()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
